package com.felipelo.etlgui.schema;

import br.com.saxes.suite.converter.ValueType;
import br.com.saxes.suite.model.TextTreeNode;
import br.com.saxes.suite.model.txt.DelimitedTXTTreeSchema;
import br.com.saxes.suite.model.txt.LineTreeNode;
import com.felipelo.etlgui.schema.model.DateMutable;
import com.felipelo.etlgui.schema.model.NumericMutable;
import com.felipelo.etlgui.schema.model.TextMutable;
import com.felipelo.etlgui.schema.model.TreeNodeMutable;
import com.felipelo.etlgui.schema.model.txt.DelimitedTXTMutable;
import com.felipelo.etlgui.schema.txt.DateNodePropTableModel;
import com.felipelo.etlgui.schema.txt.DelimitedTXTTreeSchemaPropTableModel;
import com.felipelo.etlgui.schema.txt.NumericNodePropTableModel;
import com.felipelo.etlgui.schema.txt.TextNodePropTableModel;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import javax.swing.event.TreeModelEvent;
import javax.swing.event.TreeModelListener;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeNode;
import javax.swing.tree.TreePath;

/**
 *
 * @author felipe
 */
public class TreeSchemaEditor extends javax.swing.JFrame {

	private DefaultTreeModel treeModel;
	private PropertyTableModel tableModel;
	
	private DelimitedTXTTreeSchema treeSchema;
	
	/** Creates new form TreeSchemaEditor */
	public TreeSchemaEditor() {	
		treeSchema = new DelimitedTXTTreeSchema();
		treeSchema.setName("Delimited Txt Schema");
		
		LineTreeNode _line = new LineTreeNode();
		_line.setName("Line");
		treeSchema.setRoot( _line );
		
		DelimitedTXTMutable _mTreeSchema = new DelimitedTXTMutable(treeSchema);
		TreeNodeMutable _mLine = new TreeNodeMutable(_line);
		
		_mTreeSchema.add( _mLine );
		
		treeModel = new DefaultTreeModel( _mTreeSchema );
		tableModel = new PropertyTableModel( treeModel );
		
		treeModel.addTreeModelListener( new TreeModelListener() {

			public void treeNodesChanged(TreeModelEvent e) {}
			public void treeNodesRemoved(TreeModelEvent e) {}

			public void treeNodesInserted(TreeModelEvent e) {
				for( Object _on : e.getChildren() ) {
					TreeNode[] _treeNodes = treeModel.getPathToRoot((TreeNode)_on);
					TreePath _path = new TreePath(_treeNodes);
					
					jTree1.setSelectionPath(_path);
				}
			}

			public void treeStructureChanged(TreeModelEvent e) {
				jTree1.expandPath( e.getTreePath() );
				jTree1.setSelectionPath( e.getTreePath() );
			}
		});
		
		initComponents();
	}
	
//	private void add

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jToolBar1 = new javax.swing.JToolBar();
        btnAdd = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TreeSchema Editor");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setMinimumSize(new java.awt.Dimension(100, 53));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jTree1.setModel(treeModel);
        jTree1.setCellRenderer(new com.felipelo.etlgui.schema.DefaultTreeNodeTreeCellRenderer());
        jTree1.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTree1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTree1);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jToolBar1.setFloatable(false);
        jToolBar1.setBorderPainted(false);

        btnAdd.setText("+");
        btnAdd.setToolTipText("Add Line");
        btnAdd.setFocusable(false);
        btnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdd.setPreferredSize(new java.awt.Dimension(25, 25));
        btnAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAdd);

        jButton2.setText("-");
        jButton2.setToolTipText("Remove");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setPreferredSize(new java.awt.Dimension(25, 25));
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        jPanel2.add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jSplitPane1.setLeftComponent(jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jTable1.setFont(new java.awt.Font("DejaVu Sans", 0, 11)); // NOI18N
        jTable1.setModel(tableModel);
        jTable1.setRowSelectionAllowed(false);
        jTable1.setShowVerticalLines(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);

        jPanel3.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(jPanel3);

        jPanel1.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jTree1ValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTree1ValueChanged
		DefaultMutableTreeNode _treeNode = (DefaultMutableTreeNode)jTree1.getLastSelectedPathComponent();
		
		if( _treeNode == null ) {
			tableModel.setTreeNode(null);
			return;
		}
		
		if( _treeNode instanceof DelimitedTXTMutable )
			tableModel = new DelimitedTXTTreeSchemaPropTableModel(treeModel);
		else if ( _treeNode instanceof TextMutable )
			tableModel = new TextNodePropTableModel(treeModel);
		else if ( _treeNode instanceof NumericMutable )
			tableModel = new NumericNodePropTableModel(treeModel);
		else if ( _treeNode instanceof DateMutable )
			tableModel = new DateNodePropTableModel(treeModel);
		else
			tableModel = new PropertyTableModel(treeModel);
		
		jTable1.setModel(tableModel);

		tableModel.setTreeNode( _treeNode );
		if( _treeNode.getUserObject() instanceof TextTreeNode ) {
			JComboBox _comp = new JComboBox();
			_comp.setFont(jTable1.getFont());
			_comp.setBorder(null);
			for( ValueType _valueType : ValueType.values() ) {
				_comp.addItem( _valueType );
			}
			
			jTable1.getColumnModel().getColumn(1).setCellEditor( new TextPropertyCellEditor() );
		} else {
			JTextField _jTextField = new JTextField();
			_jTextField.setBorder(null);
			_jTextField.setFont(jTable1.getFont());
			
			jTable1.getColumnModel().getColumn(1).setCellEditor( new PropertyCellEditor() );
		}
}//GEN-LAST:event_jTree1ValueChanged

private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
		DefaultMutableTreeNode _node = (DefaultMutableTreeNode) jTree1.getLastSelectedPathComponent();
		Object _userObj = _node.getUserObject();
		if( _userObj instanceof LineTreeNode ) {
			LineTreeNode _line = (LineTreeNode) _userObj;
			
			TextTreeNode _newTextNode = new TextTreeNode();
			_newTextNode.setName("New Node");
			
			_line.addChild( _newTextNode );
			
			TextMutable _newNode = new TextMutable(_newTextNode);
			
			_node.insert(_newNode, _node.getChildCount());
			treeModel.reload(_node);
		}
}//GEN-LAST:event_btnAddActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				System.out.println(info.getName());
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TreeSchemaEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TreeSchemaEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TreeSchemaEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TreeSchemaEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				
				TreeSchemaEditor d = new TreeSchemaEditor();
				d.setLocationRelativeTo(null);
				d.setVisible(true);
			}
		});
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
